GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, EXECUTE, EVENT, TRIGGER ON *.* TO 'homestead'@'localhost' IDENTIFIED BY PASSWORD '*14E65567ABDB5135D0CFD9A70B3032C179A49EE7' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `reverse_bid`.* TO 'homestead'@'localhost';