# Privilegios para `rb_user`@`localhost`

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, EXECUTE, EVENT ON *.* TO 'rb_user'@'localhost' IDENTIFIED BY PASSWORD '*22B98E2DE631450F07190CFD972041602ECBF4A2' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `reversebid`.* TO 'rb_user'@'localhost';